# Generated by Django 5.0.7 on 2024-07-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_modelblog_username_alter_modelblog_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelblog',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelblog',
            name='title',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
