# Generated by Django 5.0.7 on 2024-07-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_modelblog_content_alter_modelblog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelblog',
            name='username',
        ),
    ]
